//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booky.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Booky.Resources.WebResource", typeof(WebResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ليس لديك صلاحية لهذه الصفحة.
        /// </summary>
        public static string AccessDenied
        {
            get
            {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم العملية.
        /// </summary>
        public static string ActionName
        {
            get
            {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هل انت متأكد.
        /// </summary>
        public static string AreYouSure
        {
            get
            {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  لن تتمكن من التراجع عن هذا.
        /// </summary>
        public static string AreYouSureMsg
        {
            get
            {
                return ResourceManager.GetString("AreYouSureMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم الفئة.
        /// </summary>
        public static string CategoryName
        {
            get
            {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الفئات.
        /// </summary>
        public static string CategoryTableTitle
        {
            get
            {
                return ResourceManager.GetString("CategoryTableTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string ChangePassword
        {
            get
            {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لم يتم تغيير كلمة المرور.
        /// </summary>
        public static string ChangePasswordErr
        {
            get
            {
                return ResourceManager.GetString("ChangePasswordErr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور بنجاح.
        /// </summary>
        public static string ChangePasswordSave
        {
            get
            {
                return ResourceManager.GetString("ChangePasswordSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اغلاق.
        /// </summary>
        public static string Close
        {
            get
            {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اضف فئة جديدة.
        /// </summary>
        public static string CreateNewCategoryBtn
        {
            get
            {
                return ResourceManager.GetString("CreateNewCategoryBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to انشاء مجموعة جديدة.
        /// </summary>
        public static string CreateNewRoleBtn
        {
            get
            {
                return ResourceManager.GetString("CreateNewRoleBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اضف مستخدم جديد.
        /// </summary>
        public static string CreateNewUserBtn
        {
            get
            {
                return ResourceManager.GetString("CreateNewUserBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string Date
        {
            get
            {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم الحذف.
        /// </summary>
        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string DeleteBtn
        {
            get
            {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم حذف الفئة بنجاح.
        /// </summary>
        public static string DeleteCategoryMsg
        {
            get
            {
                return ResourceManager.GetString("DeleteCategoryMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم حذف مجموعة المستخدم بنجاح.
        /// </summary>
        public static string DeleteRoleMsg
        {
            get
            {
                return ResourceManager.GetString("DeleteRoleMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم التعديل.
        /// </summary>
        public static string Edit
        {
            get
            {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string EditBtn
        {
            get
            {
                return ResourceManager.GetString("EditBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعديل الفئة.
        /// </summary>
        public static string EditCategory
        {
            get
            {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل الفئة.
        /// </summary>
        public static string EditCategoryErrMsg
        {
            get
            {
                return ResourceManager.GetString("EditCategoryErrMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الفئة بنجاح.
        /// </summary>
        public static string EditCategoryMsg
        {
            get
            {
                return ResourceManager.GetString("EditCategoryMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لم يتم التعديل.
        /// </summary>
        public static string EditErr
        {
            get
            {
                return ResourceManager.GetString("EditErr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل مجموعة المستخدم.
        /// </summary>
        public static string EditRoleErrMsg
        {
            get
            {
                return ResourceManager.GetString("EditRoleErrMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم تعديل مجموعة المستخدم بنجاح.
        /// </summary>
        public static string EditRoleMsg
        {
            get
            {
                return ResourceManager.GetString("EditRoleMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات المستخدم.
        /// </summary>
        public static string EditUser
        {
            get
            {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل بيانات المستخدم.
        /// </summary>
        public static string EditUserErrMsg
        {
            get
            {
                return ResourceManager.GetString("EditUserErrMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات المستخدم بنجاح.
        /// </summary>
        public static string EditUserMsg
        {
            get
            {
                return ResourceManager.GetString("EditUserMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعديل مجموعة المستخدم.
        /// </summary>
        public static string EditUserRole
        {
            get
            {
                return ResourceManager.GetString("EditUserRole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الاحداث.
        /// </summary>
        public static string Events
        {
            get
            {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        public static string HomePage
        {
            get
            {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عمليات الفئات.
        /// </summary>
        public static string LogCategories
        {
            get
            {
                return ResourceManager.GetString("LogCategories", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هناك خطأ فى البيانات المسجل بها.
        /// </summary>
        public static string LoginErr
        {
            get
            {
                return ResourceManager.GetString("LoginErr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string Logout
        {
            get
            {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ادارة الكتب.
        /// </summary>
        public static string ManageBook
        {
            get
            {
                return ResourceManager.GetString("ManageBook", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ادارة المستخدمين.
        /// </summary>
        public static string ManageUsers
        {
            get
            {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هذا الاسم موجود بالفعل.
        /// </summary>
        public static string NameAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("NameAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string NoBtn
        {
            get
            {
                return ResourceManager.GetString("NoBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حسنا.
        /// </summary>
        public static string OkMsg
        {
            get
            {
                return ResourceManager.GetString("OkMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خطأ فى التسجيل.
        /// </summary>
        public static string RegisterErr
        {
            get
            {
                return ResourceManager.GetString("RegisterErr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لم يتم اضافة المستخدم.
        /// </summary>
        public static string RegisterErrMsg
        {
            get
            {
                return ResourceManager.GetString("RegisterErrMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم المجموعة.
        /// </summary>
        public static string RoleName
        {
            get
            {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  مجموعة المستخدمين.
        /// </summary>
        public static string RolesTableTitle
        {
            get
            {
                return ResourceManager.GetString("RolesTableTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ.
        /// </summary>
        public static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string SaveBtn
        {
            get
            {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ الفئة.
        /// </summary>
        public static string SaveCategoryErrMsg
        {
            get
            {
                return ResourceManager.GetString("SaveCategoryErrMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم حفظ فئة جديدة بنجاح.
        /// </summary>
        public static string SaveCategoryMsg
        {
            get
            {
                return ResourceManager.GetString("SaveCategoryMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لم يتم الحفظ.
        /// </summary>
        public static string SaveErr
        {
            get
            {
                return ResourceManager.GetString("SaveErr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ مجموعة لهذا المستخدم.
        /// </summary>
        public static string SaveRoleErrMsg
        {
            get
            {
                return ResourceManager.GetString("SaveRoleErrMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم حفظ مجموعة المستخدم بنجاح.
        /// </summary>
        public static string SaveRoleMsg
        {
            get
            {
                return ResourceManager.GetString("SaveRoleMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم حفظ مستخدم جديد بنجاح.
        /// </summary>
        public static string SaveUserMsg
        {
            get
            {
                return ResourceManager.GetString("SaveUserMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اختر مجموعة المستخدم.
        /// </summary>
        public static string SelectUserRole
        {
            get
            {
                return ResourceManager.GetString("SelectUserRole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اعد كتابة كلمة المرور.
        /// </summary>
        public static string UserConfirmPassword
        {
            get
            {
                return ResourceManager.GetString("UserConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى.
        /// </summary>
        public static string UserEmail
        {
            get
            {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to صورة المستخدم.
        /// </summary>
        public static string UserImage
        {
            get
            {
                return ResourceManager.GetString("UserImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تفعيل المستخدم.
        /// </summary>
        public static string UserIsActive
        {
            get
            {
                return ResourceManager.GetString("UserIsActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string UserName
        {
            get
            {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string UserPassword
        {
            get
            {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string UsersTableTitle
        {
            get
            {
                return ResourceManager.GetString("UsersTableTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string YesBtn
        {
            get
            {
                return ResourceManager.GetString("YesBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to أضف صلاحيات.
        /// </summary>
        public static string AddPermissionsBtn
        {
            get
            {
                return ResourceManager.GetString("AddPermissionsBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ادارة الصلاحيات ل.
        /// </summary>
        public static string ManagePermission
        {
            get
            {
                return ResourceManager.GetString("ManagePermission", resourceCulture);
            }
        }
    }
}
